from app.models import db, Question


def seed_questions():
    question1 = Question(userId = 8, HomeId = 1, question = "Can I See Your Real Estate License?")
    question2 = Question(userId = 3, HomeId = 2, question = "Can You Pass Along a List of Referrals?")
    question3 = Question(userId = 3, HomeId = 3, question = "What Is Your Listings’ Average Days on Market?")
    question4 = Question(userId = 5, HomeId = 4, question = "What Is Your List-to-Price Ratio?")
    question5 = Question(userId = 4, HomeId = 5, question = "Have You Sold Homes in This Neighborhood?")
    question6 = Question(userId = 7, HomeId = 6, question = "Have You Sold Homes in This Price Range?")
    question7 = Question(userId = 1, HomeId = 7, question = "What Is Your List-to-Price Ratio?")
    question8 = Question(userId = 1, HomeId = 8, question = "How Long Have You Been a Real Estate Agent?")
    question9 = Question(userId = 10, HomeId = 9, question = "Are You a Part-Time or Full-Time Agent?")
    question10 = Question(userId = 10, HomeId = 10, question = "How Many Sellers Are You Currently Representing?")
    question11 = Question(userId = 7, HomeId = 11, question = "What’s the Ratio Between Buyers and Sellers You Represent?")
    question12 = Question(userId = 6, HomeId = 12, question = "Will I Be Working With You Directly or a Team?")
    question13 = Question(userId = 10, HomeId = 13, question = "How Do You Plan to Market the Home?")
    question14 = Question(userId = 7, HomeId = 14, question = "Do You Have XYZ in Your Network?")
    question15 = Question(userId = 8, HomeId = 15, question = "How Do Your Realtor Fees Work?")
    question16 = Question(userId = 2, HomeId = 16, question = "Can You Explain the Home Selling Process from Start to Finish?")
    question17 = Question(userId = 6, HomeId = 17, question = "What’s the Best Way to Contact You?")
    question18 = Question(userId = 6, HomeId = 18, question = "Can I See a Written Comparative Market Analysis?")
    question19 = Question(userId = 10, HomeId = 19, question = "What Price Will Sell This House?")
    question20 = Question(userId = 5, HomeId = 20, question = "What Do You Believe Will Sell This Home?")
    question21 = Question(userId = 10, HomeId = 21, question = "How Can We Best Work Together to Sell This House?")
    question22 = Question(userId = 4, HomeId = 22, question = "What Can I Do to Get This House Ready for Showings?")
    question23 = Question(userId = 2, HomeId = 23, question = "Do I Need Professional Stagers for My Home?")
    question24 = Question(userId = 1, HomeId = 24, question = "What Should I Already Be Packing Up?")
    question25 = Question(userId = 10, HomeId = 25, question = "What Are The Closing Costs?")
    question26 = Question(userId = 5, HomeId = 1, question = "Can I See Your Real Estate License?")
    question27 = Question(userId = 8, HomeId = 2, question = "Can You Pass Along a List of Referrals?")
    question28 = Question(userId = 5, HomeId = 3, question = "What Is Your Listings’ Average Days on Market?")
    question29 = Question(userId = 3, HomeId = 4, question = "What Is Your List-to-Price Ratio?")
    question30 = Question(userId = 2, HomeId = 1, question = "Have You Sold Homes in This Neighborhood?")
    question31 = Question(userId = 6, HomeId = 2, question = "Have You Sold Homes in This Price Range?")
    question32 = Question(userId = 6, HomeId = 3, question = "What Is Your List-to-Price Ratio?")
    question33 = Question(userId = 9, HomeId = 4, question = "How Long Have You Been a Real Estate Agent?")
    question34 = Question(userId = 5, HomeId = 5, question = "Are You a Part-Time or Full-Time Agent?")
    question35 = Question(userId = 8, HomeId = 6, question = "How Many Sellers Are You Currently Representing?")
    question36 = Question(userId = 6, HomeId = 7, question = "What’s the Ratio Between Buyers and Sellers You Represent?")
    question37 = Question(userId = 2, HomeId = 8, question = "Will I Be Working With You Directly or a Team?")
    question38 = Question(userId = 2, HomeId = 9, question = "How Do You Plan to Market the Home?")
    question39 = Question(userId = 10, HomeId = 10, question = "Do You Have XYZ in Your Network?")
    question40 = Question(userId = 4, HomeId = 11, question = "How Do Your Realtor Fees Work?")
    question41 = Question(userId = 8, HomeId = 12, question = "Can You Explain the Home Selling Process from Start to Finish?")
    question42 = Question(userId = 1, HomeId = 13, question = "What’s the Best Way to Contact You?")
    question43 = Question(userId = 1, HomeId = 14, question = "Can I See a Written Comparative Market Analysis?")
    question44 = Question(userId = 10, HomeId = 15, question = "What Price Will Sell This House?")
    question45 = Question(userId = 2, HomeId = 16, question = "What Do You Believe Will Sell This Home?")
    question46 = Question(userId = 5, HomeId = 17, question = "How Can We Best Work Together to Sell This House?")
    question47 = Question(userId = 5, HomeId = 18, question = "What Can I Do to Get This House Ready for Showings?")
    question48 = Question(userId = 4, HomeId = 19, question = "Do I Need Professional Stagers for My Home?")
    question49 = Question(userId = 8, HomeId = 20, question = "What Should I Already Be Packing Up?")
    question50 = Question(userId = 10, HomeId = 21, question = "What Are The Closing Costs?")
    question51 = Question(userId = 8, HomeId = 22, question = "Can I See Your Real Estate License?")
    question52 = Question(userId = 10, HomeId = 23, question = "Can You Pass Along a List of Referrals?")
    question53 = Question(userId = 6, HomeId = 24, question = "What Is Your Listings’ Average Days on Market?")
    question54 = Question(userId = 5, HomeId = 25, question = "What Is Your List-to-Price Ratio?")
    question55 = Question(userId = 4, HomeId = 6, question = "Have You Sold Homes in This Neighborhood?")
    question56 = Question(userId = 2, HomeId = 7, question = "Have You Sold Homes in This Price Range?")
    question57 = Question(userId = 3, HomeId = 8, question = "What Is Your List-to-Price Ratio?")
    question58 = Question(userId = 8, HomeId = 9, question = "How Long Have You Been a Real Estate Agent?")
    question59 = Question(userId = 2, HomeId = 10, question = "Are You a Part-Time or Full-Time Agent?")
    question60 = Question(userId = 8, HomeId = 1, question = "How Many Sellers Are You Currently Representing?")
    question61 = Question(userId = 8, HomeId = 2, question = "What’s the Ratio Between Buyers and Sellers You Represent?")
    question62 = Question(userId = 8, HomeId = 3, question = "Will I Be Working With You Directly or a Team?")
    question63 = Question(userId = 4, HomeId = 4, question = "How Do You Plan to Market the Home?")
    question64 = Question(userId = 3, HomeId = 5, question = "Do You Have XYZ in Your Network?")
    question65 = Question(userId = 6, HomeId = 6, question = "How Do Your Realtor Fees Work?")
    question66 = Question(userId = 7, HomeId = 7, question = "Can You Explain the Home Selling Process from Start to Finish?")
    question67 = Question(userId = 5, HomeId = 8, question = "What’s the Best Way to Contact You?")
    question68 = Question(userId = 3, HomeId = 9, question = "Can I See a Written Comparative Market Analysis?")
    question69 = Question(userId = 6, HomeId = 10, question = "What Price Will Sell This House?")
    question70 = Question(userId = 1, HomeId = 11, question = "What Do You Believe Will Sell This Home?")
    question71 = Question(userId = 8, HomeId = 12, question = "How Can We Best Work Together to Sell This House?")
    question72 = Question(userId = 3, HomeId = 13, question = "What Can I Do to Get This House Ready for Showings?")
    question73 = Question(userId = 3, HomeId = 14, question = "Do I Need Professional Stagers for My Home?")
    question74 = Question(userId = 7, HomeId = 15, question = "What Should I Already Be Packing Up?")
    question75 = Question(userId = 2, HomeId = 16, question = "What Are The Closing Costs?")
    question76 = Question(userId = 9, HomeId = 17, question = "Can I See Your Real Estate License?")
    question77 = Question(userId = 2, HomeId = 18, question = "Can You Pass Along a List of Referrals?")
    question78 = Question(userId = 5, HomeId = 19, question = "What Is Your Listings’ Average Days on Market?")
    question79 = Question(userId = 2, HomeId = 20, question = "What Is Your List-to-Price Ratio?")
    question80 = Question(userId = 1, HomeId = 21, question = "Have You Sold Homes in This Neighborhood?")
    question81 = Question(userId = 8, HomeId = 22, question = "Have You Sold Homes in This Price Range?")
    question82 = Question(userId = 3, HomeId = 23, question = "What Is Your List-to-Price Ratio?")
    question83 = Question(userId = 3, HomeId = 24, question = "How Long Have You Been a Real Estate Agent?")
    question84 = Question(userId = 5, HomeId = 25, question = "Are You a Part-Time or Full-Time Agent?")
    question85 = Question(userId = 4, HomeId = 11, question = "How Many Sellers Are You Currently Representing?")
    question86 = Question(userId = 7, HomeId = 12, question = "What’s the Ratio Between Buyers and Sellers You Represent?")
    question87 = Question(userId = 1, HomeId = 13, question = "Will I Be Working With You Directly or a Team?")
    question88 = Question(userId = 1, HomeId = 1, question = "How Do You Plan to Market the Home?")
    question89 = Question(userId = 10, HomeId = 2, question = "Do You Have XYZ in Your Network?")
    question90 = Question(userId = 10, HomeId = 3, question = "How Do Your Realtor Fees Work?")
    question91 = Question(userId = 7, HomeId = 4, question = "Can You Explain the Home Selling Process from Start to Finish?")
    question92 = Question(userId = 6, HomeId = 5, question = "What’s the Best Way to Contact You?")
    question93 = Question(userId = 10, HomeId = 6, question = "Can I See a Written Comparative Market Analysis?")
    question94 = Question(userId = 7, HomeId = 7, question = "What Price Will Sell This House?")
    question95 = Question(userId = 8, HomeId = 8, question = "What Do You Believe Will Sell This Home?")
    question96 = Question(userId = 2, HomeId = 9, question = "How Can We Best Work Together to Sell This House?")
    question97 = Question(userId = 6, HomeId = 10, question = "What Can I Do to Get This House Ready for Showings?")
    question98 = Question(userId = 6, HomeId = 11, question = "Do I Need Professional Stagers for My Home?")
    question99 = Question(userId = 10, HomeId = 12, question = "What Should I Already Be Packing Up?")
    question100 = Question(userId = 5, HomeId = 13, question = "What Are The Closing Costs?")
    question101 = Question(userId = 10, HomeId = 14, question = "Can I See Your Real Estate License?")
    question102 = Question(userId = 4, HomeId = 15, question = "Can You Pass Along a List of Referrals?")
    question103 = Question(userId = 2, HomeId = 16, question = "What Is Your Listings’ Average Days on Market?")
    question104 = Question(userId = 1, HomeId = 17, question = "What Is Your List-to-Price Ratio?")
    question105 = Question(userId = 10, HomeId = 18, question = "Have You Sold Homes in This Neighborhood?")
    question106 = Question(userId = 5, HomeId = 19, question = "Have You Sold Homes in This Price Range?")
    question107 = Question(userId = 8, HomeId = 20, question = "What Is Your List-to-Price Ratio?")
    question108 = Question(userId = 5, HomeId = 21, question = "How Long Have You Been a Real Estate Agent?")
    question109 = Question(userId = 3, HomeId = 22, question = "Are You a Part-Time or Full-Time Agent?")
    question110 = Question(userId = 2, HomeId = 23, question = "How Many Sellers Are You Currently Representing?")
    question111 = Question(userId = 6, HomeId = 24, question = "What’s the Ratio Between Buyers and Sellers You Represent?")
    question112 = Question(userId = 6, HomeId = 25, question = "Will I Be Working With You Directly or a Team?")
    question113 = Question(userId = 9, HomeId = 14, question = "How Do You Plan to Market the Home?")
    question114 = Question(userId = 5, HomeId = 15, question = "Do You Have XYZ in Your Network?")
    question115 = Question(userId = 8, HomeId = 16, question = "How Do Your Realtor Fees Work?")
    question116 = Question(userId = 6, HomeId = 17, question = "Can You Explain the Home Selling Process from Start to Finish?")
    question117 = Question(userId = 2, HomeId = 1, question = "What’s the Best Way to Contact You?")
    question118 = Question(userId = 2, HomeId = 2, question = "Can I See a Written Comparative Market Analysis?")
    question119 = Question(userId = 10, HomeId = 3, question = "What Price Will Sell This House?")
    question120 = Question(userId = 4, HomeId = 4, question = "What Do You Believe Will Sell This Home?")
    question121 = Question(userId = 8, HomeId = 5, question = "How Can We Best Work Together to Sell This House?")
    question122 = Question(userId = 1, HomeId = 6, question = "What Can I Do to Get This House Ready for Showings?")
    question123 = Question(userId = 1, HomeId = 7, question = "Do I Need Professional Stagers for My Home?")
    question124 = Question(userId = 10, HomeId = 8, question = "What Should I Already Be Packing Up?")
    question125 = Question(userId = 2, HomeId = 9, question = "What Are The Closing Costs?")
    question126 = Question(userId = 5, HomeId = 10, question = "Can I See Your Real Estate License?")
    question127 = Question(userId = 5, HomeId = 11, question = "Can You Pass Along a List of Referrals?")
    question128 = Question(userId = 4, HomeId = 12, question = "What Is Your Listings’ Average Days on Market?")
    question129 = Question(userId = 8, HomeId = 13, question = "What Is Your List-to-Price Ratio?")
    question130 = Question(userId = 10, HomeId = 14, question = "Have You Sold Homes in This Neighborhood?")
    question131 = Question(userId = 8, HomeId = 15, question = "Have You Sold Homes in This Price Range?")
    question132 = Question(userId = 10, HomeId = 16, question = "What Is Your List-to-Price Ratio?")
    question133 = Question(userId = 6, HomeId = 17, question = "How Long Have You Been a Real Estate Agent?")
    question134 = Question(userId = 5, HomeId = 18, question = "Are You a Part-Time or Full-Time Agent?")
    question135 = Question(userId = 4, HomeId = 19, question = "How Many Sellers Are You Currently Representing?")
    question136 = Question(userId = 2, HomeId = 20, question = "What’s the Ratio Between Buyers and Sellers You Represent?")
    question137 = Question(userId = 3, HomeId = 21, question = "Will I Be Working With You Directly or a Team?")
    question138 = Question(userId = 8, HomeId = 22, question = "How Do You Plan to Market the Home?")
    question139 = Question(userId = 2, HomeId = 23, question = "Do You Have XYZ in Your Network?")
    question140 = Question(userId = 8, HomeId = 24, question = "How Do Your Realtor Fees Work?")
    question141 = Question(userId = 8, HomeId = 25, question = "Can You Explain the Home Selling Process from Start to Finish?")
    question142 = Question(userId = 8, HomeId = 18, question = "What’s the Best Way to Contact You?")
    question143 = Question(userId = 4, HomeId = 19, question = "Can I See a Written Comparative Market Analysis?")
    question144 = Question(userId = 3, HomeId = 20, question = "What Price Will Sell This House?")
    question145 = Question(userId = 6, HomeId = 1, question = "What Do You Believe Will Sell This Home?")
    question146 = Question(userId = 7, HomeId = 2, question = "How Can We Best Work Together to Sell This House?")
    question147 = Question(userId = 5, HomeId = 3, question = "What Can I Do to Get This House Ready for Showings?")
    question148 = Question(userId = 3, HomeId = 4, question = "Do I Need Professional Stagers for My Home?")
    question149 = Question(userId = 6, HomeId = 5, question = "What Should I Already Be Packing Up?")
    question150 = Question(userId = 1, HomeId = 6, question = "What Are The Closing Costs?")
    question151 = Question(userId = 8, HomeId = 7, question = "Can I See Your Real Estate License?")
    question152 = Question(userId = 3, HomeId = 8, question = "Can You Pass Along a List of Referrals?")
    question153 = Question(userId = 3, HomeId = 9, question = "What Is Your Listings’ Average Days on Market?")
    question154 = Question(userId = 7, HomeId = 10, question = "What Is Your List-to-Price Ratio?")
    question155 = Question(userId = 2, HomeId = 11, question = "Have You Sold Homes in This Neighborhood?")
    question156 = Question(userId = 9, HomeId = 12, question = "Have You Sold Homes in This Price Range?")
    question157 = Question(userId = 2, HomeId = 13, question = "What Is Your List-to-Price Ratio?")
    question158 = Question(userId = 5, HomeId = 14, question = "How Long Have You Been a Real Estate Agent?")
    question159 = Question(userId = 2, HomeId = 15, question = "Are You a Part-Time or Full-Time Agent?")
    question160 = Question(userId = 1, HomeId = 16, question = "How Many Sellers Are You Currently Representing?")
    question161 = Question(userId = 8, HomeId = 17, question = "What’s the Ratio Between Buyers and Sellers You Represent?")
    question162 = Question(userId = 3, HomeId = 18, question = "Will I Be Working With You Directly or a Team?")
    question163 = Question(userId = 3, HomeId = 19, question = "How Do You Plan to Market the Home?")
    question164 = Question(userId = 5, HomeId = 20, question = "Do You Have XYZ in Your Network?")
    question165 = Question(userId = 4, HomeId = 21, question = "How Do Your Realtor Fees Work?")
    question166 = Question(userId = 7, HomeId = 22, question = "Can You Explain the Home Selling Process from Start to Finish?")
    question167 = Question(userId = 1, HomeId = 23, question = "What’s the Best Way to Contact You?")
    question168 = Question(userId = 1, HomeId = 24, question = "Can I See a Written Comparative Market Analysis?")
    question169 = Question(userId = 10, HomeId = 25, question = "What Price Will Sell This House?")
    question170 = Question(userId = 10, HomeId = 21, question = "What Do You Believe Will Sell This Home?")
    question171 = Question(userId = 7, HomeId = 22, question = "How Can We Best Work Together to Sell This House?")
    question172 = Question(userId = 6, HomeId = 23, question = "What Can I Do to Get This House Ready for Showings?")
    question173 = Question(userId = 10, HomeId = 24, question = "Do I Need Professional Stagers for My Home?")
    question174 = Question(userId = 7, HomeId = 25, question = "What Should I Already Be Packing Up?")
    question175 = Question(userId = 8, HomeId = 1, question = "What Are The Closing Costs?")
    question176 = Question(userId = 2, HomeId = 25, question = "Can I See Your Real Estate License?")
    question177 = Question(userId = 6, HomeId = 1, question = "Can You Pass Along a List of Referrals?")
    question178 = Question(userId = 6, HomeId = 2, question = "What Is Your Listings’ Average Days on Market?")
    question179 = Question(userId = 10, HomeId = 3, question = "What Is Your List-to-Price Ratio?")
    question180 = Question(userId = 5, HomeId = 4, question = "Have You Sold Homes in This Neighborhood?")
    question181 = Question(userId = 10, HomeId = 5, question = "Have You Sold Homes in This Price Range?")
    question182 = Question(userId = 4, HomeId = 6, question = "What Is Your List-to-Price Ratio?")
    question183 = Question(userId = 2, HomeId = 7, question = "How Long Have You Been a Real Estate Agent?")
    question184 = Question(userId = 1, HomeId = 8, question = "Are You a Part-Time or Full-Time Agent?")
    question185 = Question(userId = 10, HomeId = 9, question = "How Many Sellers Are You Currently Representing?")
    question186 = Question(userId = 5, HomeId = 10, question = "What’s the Ratio Between Buyers and Sellers You Represent?")
    question187 = Question(userId = 8, HomeId = 11, question = "Will I Be Working With You Directly or a Team?")
    question188 = Question(userId = 5, HomeId = 12, question = "How Do You Plan to Market the Home?")
    question189 = Question(userId = 3, HomeId = 13, question = "Do You Have XYZ in Your Network?")
    question190 = Question(userId = 2, HomeId = 14, question = "How Do Your Realtor Fees Work?")
    question191 = Question(userId = 6, HomeId = 15, question = "Can You Explain the Home Selling Process from Start to Finish?")
    question192 = Question(userId = 6, HomeId = 16, question = "What’s the Best Way to Contact You?")
    question193 = Question(userId = 9, HomeId = 17, question = "Can I See a Written Comparative Market Analysis?")
    question194 = Question(userId = 5, HomeId = 18, question = "What Price Will Sell This House?")
    question195 = Question(userId = 8, HomeId = 19, question = "What Do You Believe Will Sell This Home?")
    question196 = Question(userId = 6, HomeId = 20, question = "How Can We Best Work Together to Sell This House?")
    question197 = Question(userId = 2, HomeId = 21, question = "What Can I Do to Get This House Ready for Showings?")
    question198 = Question(userId = 2, HomeId = 22, question = "Do I Need Professional Stagers for My Home?")
    question199 = Question(userId = 10, HomeId = 23, question = "What Should I Already Be Packing Up?")
    question200 = Question(userId = 4, HomeId = 24, question = "What Are The Closing Costs?")


    db.session.add(question1)
    db.session.add(question2)
    db.session.add(question3)
    db.session.add(question4)
    db.session.add(question5)
    db.session.add(question6)
    db.session.add(question7)
    db.session.add(question8)
    db.session.add(question9)
    db.session.add(question10)
    db.session.add(question11)
    db.session.add(question12)
    db.session.add(question13)
    db.session.add(question14)
    db.session.add(question15)
    db.session.add(question16)
    db.session.add(question17)
    db.session.add(question18)
    db.session.add(question19)
    db.session.add(question20)
    db.session.add(question21)
    db.session.add(question22)
    db.session.add(question23)
    db.session.add(question24)
    db.session.add(question25)
    db.session.add(question26)
    db.session.add(question27)
    db.session.add(question28)
    db.session.add(question29)
    db.session.add(question30)
    db.session.add(question31)
    db.session.add(question32)
    db.session.add(question33)
    db.session.add(question34)
    db.session.add(question35)
    db.session.add(question36)
    db.session.add(question37)
    db.session.add(question38)
    db.session.add(question39)
    db.session.add(question40)
    db.session.add(question41)
    db.session.add(question42)
    db.session.add(question43)
    db.session.add(question44)
    db.session.add(question45)
    db.session.add(question46)
    db.session.add(question47)
    db.session.add(question48)
    db.session.add(question49)
    db.session.add(question50)
    db.session.add(question51)
    db.session.add(question52)
    db.session.add(question53)
    db.session.add(question54)
    db.session.add(question55)
    db.session.add(question56)
    db.session.add(question57)
    db.session.add(question58)
    db.session.add(question59)
    db.session.add(question60)
    db.session.add(question61)
    db.session.add(question62)
    db.session.add(question63)
    db.session.add(question64)
    db.session.add(question65)
    db.session.add(question66)
    db.session.add(question67)
    db.session.add(question68)
    db.session.add(question69)
    db.session.add(question70)
    db.session.add(question71)
    db.session.add(question72)
    db.session.add(question73)
    db.session.add(question74)
    db.session.add(question75)
    db.session.add(question76)
    db.session.add(question77)
    db.session.add(question78)
    db.session.add(question79)
    db.session.add(question80)
    db.session.add(question81)
    db.session.add(question82)
    db.session.add(question83)
    db.session.add(question84)
    db.session.add(question85)
    db.session.add(question86)
    db.session.add(question87)
    db.session.add(question88)
    db.session.add(question89)
    db.session.add(question90)
    db.session.add(question91)
    db.session.add(question92)
    db.session.add(question93)
    db.session.add(question94)
    db.session.add(question95)
    db.session.add(question96)
    db.session.add(question97)
    db.session.add(question98)
    db.session.add(question99)
    db.session.add(question100)
    db.session.add(question101)
    db.session.add(question102)
    db.session.add(question103)
    db.session.add(question104)
    db.session.add(question105)
    db.session.add(question106)
    db.session.add(question107)
    db.session.add(question108)
    db.session.add(question109)
    db.session.add(question110)
    db.session.add(question111)
    db.session.add(question112)
    db.session.add(question113)
    db.session.add(question114)
    db.session.add(question115)
    db.session.add(question116)
    db.session.add(question117)
    db.session.add(question118)
    db.session.add(question119)
    db.session.add(question120)
    db.session.add(question121)
    db.session.add(question122)
    db.session.add(question123)
    db.session.add(question124)
    db.session.add(question125)
    db.session.add(question126)
    db.session.add(question127)
    db.session.add(question128)
    db.session.add(question129)
    db.session.add(question130)
    db.session.add(question131)
    db.session.add(question132)
    db.session.add(question133)
    db.session.add(question134)
    db.session.add(question135)
    db.session.add(question136)
    db.session.add(question137)
    db.session.add(question138)
    db.session.add(question139)
    db.session.add(question140)
    db.session.add(question141)
    db.session.add(question142)
    db.session.add(question143)
    db.session.add(question144)
    db.session.add(question145)
    db.session.add(question146)
    db.session.add(question147)
    db.session.add(question148)
    db.session.add(question149)
    db.session.add(question150)
    db.session.add(question151)
    db.session.add(question152)
    db.session.add(question153)
    db.session.add(question154)
    db.session.add(question155)
    db.session.add(question156)
    db.session.add(question157)
    db.session.add(question158)
    db.session.add(question159)
    db.session.add(question160)
    db.session.add(question161)
    db.session.add(question162)
    db.session.add(question163)
    db.session.add(question164)
    db.session.add(question165)
    db.session.add(question166)
    db.session.add(question167)
    db.session.add(question168)
    db.session.add(question169)
    db.session.add(question170)
    db.session.add(question171)
    db.session.add(question172)
    db.session.add(question173)
    db.session.add(question174)
    db.session.add(question175)
    db.session.add(question176)
    db.session.add(question177)
    db.session.add(question178)
    db.session.add(question179)
    db.session.add(question180)
    db.session.add(question181)
    db.session.add(question182)
    db.session.add(question183)
    db.session.add(question184)
    db.session.add(question185)
    db.session.add(question186)
    db.session.add(question187)
    db.session.add(question188)
    db.session.add(question189)
    db.session.add(question190)
    db.session.add(question191)
    db.session.add(question192)
    db.session.add(question193)
    db.session.add(question194)
    db.session.add(question195)
    db.session.add(question196)
    db.session.add(question197)
    db.session.add(question198)
    db.session.add(question199)
    db.session.add(question200)

    db.session.commit()


def undo_questions():
    db.session.execute('TRUNCATE questions RESTART IDENTITY CASCADE;')
    db.session.commit()




