name: Python application

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
    - 
      name: Login to Heroku Container registry
      run: heroku container:login
    - 
      name: Checkout code from github 
      uses: actions/checkout@v2
    - 
      name: Build and push
      run: heroku container:push -a gotahome web
    - 
      name: Release
      run: heroku container:release -a gotahome web
